import type { Metadata } from "next";
import localFont from "next/font/local";
import { CartProvider } from "../context/CartContext";
import Header from "@/components/header";
import "./globals.css";

// تعریف فونت‌های محلی
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// متادیتا برای صفحه اصلی
export const metadata: Metadata = {
  title: "Training Program for Better Learning",
  description: "Generated by create next app",
};

// تعریف نوع پروپ‌ها برای RootLayout
interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <CartProvider>
        <Header />
          <div className="min-h-screen flex flex-col">
            {/* محتوای اصلی سایت */}
            {children}
          </div>
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
